version: '3'

services: 
  postgres:
    image: 'postgres:latest' #from hub.docker.com
  redis:
    image: 'redis:latest'
  server:
    build:
      dockerfile: Dockerfile.dev #just specifying the name without the path 
      context: ./server #current working directory
    volumes:
      - /app/node_modules #leave that folder as is, do not do anything with it
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379 # from hub.docker.com
      - PGUSER=postgres # default username
      - PGHOST=postgres # service name from this file
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password # from docker hub
      - PGPORT=5432 #

      
